[package]
name = "wasi-experimental-http-wasmtime-sample"
version = "0.1.0"
authors = ["Radu Matei <radu.matei@microsoft.com>"]
edition = "2018"

[dev-dependencies]
anyhow = "1.0"
futures = "0.3"
http = "0.2"
reqwest = { version = "0.11", default-features = true, features = ["json", "blocking"] }
tokio = { version = "1.4.0", features = ["full"] }
wasmtime = "0.25.0"
wasmtime-wasi = "0.25.0"
wasi-common = "0.25.0"
wasi-cap-std-sync = "0.25.0"
wasi-experimental-http = { path = "crates/wasi-experimental-http" }
wasi-experimental-http-wasmtime = { path = "crates/wasi-experimental-http-wasmtime" }

[workspace]
members = [
    "crates/wasi-experimental-http",
    "crates/wasi-experimental-http-wasmtime",
    "tests/rust"
]
